import type { Metadata } from "next";
import { Geist, Geist_Mono } from "next/font/google";
import "./globals.css";
import { ClerkProvider } from "@clerk/nextjs";
import { Toaster } from "@/components/ui/toaster"

// import NEXT_PUBLIC_CLERK_PUBLISHABLE_KEY from 
require('dotenv').config()

// Fonts
const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});

const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});

// Metadata for the app
export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({ children }: Readonly<{ children: React.ReactNode }>) {
  return (
    <html lang="en">
      <ClerkProvider
        publishableKey={process.env.NEXT_PUBLIC_CLERK_PUBLISHABLE_KEY}
      // appearance={{
      //   variables: {
      //     colorText: "#fff",
      //     colorBackground: '#1c1f2e',
      //     colorPrimary: '#30E78F9',
      //     colorInputBackground: '#252a41',
      //     colorInputText: '#fff',
      //   },
      // }}
      >
        <body className={`${geistSans.variable} ${geistMono.variable} bg-dark-2 antialiased`}>
          {children}
          <Toaster />
        </body>

      </ClerkProvider>
    </html>
  );
}
